# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: 寒夏汢
keyword: 寒夏汢,寒夏汢的博客,寒夏汢的小站
description: 寒夏汢的小站，致力于分享一些技术教程和有趣的技术实践。
author: 寒夏汢
language: zh-CN

url: https://hanxiatu.com
root: /
permalink: post/:title.html

# seo优化各个浏览器的验证信息
beian: 
seo_title: 寒夏汢 # 子页面的后缀，效果： 关于我 | 寒夏汢，如果与title一致，则可以不设置
seo:
  google_site_verification: 19ixTFj-X-rXuvZFvR1PMkqSHMXZ5GjN7nhYdYYFm-c
  baidu_site_verification: p7Pz3jlx4t
  ms_site_verification: 7E2AEE3378AC93764DEAB411177A21A1
  _360_site_verification: 5c7e8a1fdbf35ed6003c48733208f705 # 不能以数字开头，所以加上了下划线

# 开启博客资源的相对链接 https://hexo.io/zh-cn/docs/asset-folders
post_asset_folder: true

# Site settings
header_img: img/bg.jpg
header_icon: img/icon.jpg

github_username: hanxiatu-fc

theme: geektutu

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/hanxiatu-fc/hanxiatu-fc.github.io.git
  branch: master

gitalk:
  client_id: 'c1fdd456a4caae5f7df0'
  client_secret: 'b2674451e21feae50520f99337ec15d2aebe7879'
  repo: 'hexo-theme-geektutu'
  owner: 'geektutu'

# alipay wechatpay 的二维码转换的网址，不使用二维码图片，提高加载速率。
# https://cli.im/deqr 可将二维码转为网址
reward:
  alipay: https://qr.alipay.com/fkx08108fho2pxknz5kyu48
  wechat: wxp://f2f0Ti_imJaiPKxLF1-zDdS1ttG7snD59SWz

related_links:
- link: https://github.com/hanxiatu-fc
  img: img/related_links/github.png
- link: https://geektutu.com
  img: img/related_links/geektutu.png
- link: mailto:hanxiatu@gmail.com?subject=From Hanxiatu's Blog
  img: img/related_links/email.png

ba_auto_push: true # Baidu 自动推送，以下均为可选配置
ba_track_id: 1a0ec33b1aa # Baidu Analytics
cnzz_track_id: 123649 # CNZZ Analytics
#google_analysis: UA-141425-1 # Google Analytics
#google_ad_client: ca-pub-939225546 # Google Ad